# Genesis Configuration
- name: check if genesis_file is gz or not
  when: genesis_file is defined
  stat:
    path: '{{genesis_file}}'
    get_mime: true
  delegate_to: localhost
  become: false
  register: file_type

- name: File type of {{genesis_file}}
  when: genesis_file is defined
  debug:
    msg: '{{file_type.stat.mimetype}}'

- name: gzip the file if not zipped
  when:
    - genesis_file is defined
    - file_type.stat.mimetype != "application/gzip"
  archive:
    path: '{{genesis_file}}'
    dest: '{{genesis_file}}.gz'
    format: gz
  delegate_to: localhost
  become: false

- name: set genesis_file to include .gz
  when:
    - genesis_file is defined
    - file_type.stat.mimetype != "application/gzip"
  set_fact:
    genesis_file: '{{ genesis_file }}.gz'

- name: copy {{genesis_file}} to remote server
  when: genesis_file is defined
  copy:
    src: '{{genesis_file}}'
    dest: '{{node_user_home}}/genesis.json.gz'
    owner: '{{node_user}}'
    group: '{{node_user}}'

- name: extract {{genesis_file}} to {{chain_home}}/config/genesis.json
  when: genesis_file is defined
  shell: |
    gunzip -c $HOME/genesis.json.gz > {{chain_home}}/config/genesis.json
  become_user: "{{node_user}}"

- name: verify genesis file
  when: genesis_shasum is defined
  # Throw an error if shasum doesn't match
  shell: |
    GENESIS_SHASUM="$(sha256sum {{ chain_home }}/config/genesis.json)"
    if [ $GENESIS_SHASUM != {{ genesis_shasum }} ]; then
      exit 1
    fi
      exit 0
  become_user: "{{node_user}}"